import type { Metadata } from "next";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import MenuBar from "@/components/MenuBar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <SidebarProvider>
        <AppSidebar />

      <body
        className=""
      >
        <SidebarTrigger />
        <MenuBar/>
        {children}
      </body>
      </SidebarProvider>
    </html>
  );
}
